"""
storage/models.py
──────────────────
SQLAlchemy ORM models — the five tables that power M11 persistence and RAG.

Table layout:
  runs            — one row per pipeline run (lifecycle metadata)
  agent_artifacts — one row per (run × ticker × agent); holds output JSON + vector embedding
  run_events      — AuditLogger write path; one row per agent call (tokens, cost, latency)
  run_digests     — serialised FinalRecommendation per run (for list-runs / show-run)
  data_provenance — news source tracking per (run × ticker)

Embeddings are stored in agent_artifacts.embedding (pgvector Vector(3072)).
The vector dimension matches gemini-embedding-2 output (3072 dims).

Usage:
    from storage.models import Base, RunRecord, AgentArtifact
    # Tables are created via storage.db.init_db()
"""

import uuid
from datetime import UTC, date, datetime
from typing import Optional

from chive_shared.schemas.run import EventStatus

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    CheckConstraint,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, JSON, JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    pass


class AgentArtifact(Base):
    """
    One row per (run × ticker × agent) — the core RAG source table.

    output_json stores the full serialised agent output (StockVerdict,
    ScenarioResearchOutput, FinalRecommendation, etc.).

    embedding is the 3072-dim vector from gemini-embedding-2, generated by
    RAGIndexer after each run. Null until indexing completes.

    Lifecycle:
      memory_type="raw_report"       — full output JSON, kept for RAG_RETENTION_DAYS (90 days)
      memory_type="archived_summary" — quarter-anchored compressed summary; kept indefinitely
                                       (or until RAG_ARCHIVE_RETENTION_DAYS if set)

    At 90 days, RAGArchiver compresses each raw_report into an archived_summary,
    re-embeds the summary, and deletes the original. This mirrors how investment
    firms retain quarterly research dossiers without losing YoY context.

    sector is populated at indexing time from the data provider's fundamentals
    response (GICS sector string). It enables sector-scoped hybrid retrieval —
    e.g. "retrieve all Technology sector verdicts from last quarter" — which is
    how sell-side analysts do relative-value and sector-rotation analysis.
    """

    __tablename__ = "agent_artifacts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    ticker: Mapped[Optional[str]] = mapped_column(
        String(20), nullable=True, index=True
    )  # None for portfolio-level artifacts (FinalRecommendation)
    agent_name: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    model_used: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    input_tokens: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    output_tokens: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    latency_ms: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    memory_type: Mapped[str] = mapped_column(
        String(32), nullable=False, default="raw_report", index=True
    )  # "raw_report" | "archived_summary"
    sector: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True, index=True
    )  # GICS sector (e.g. "Technology", "Financials") — None for portfolio-level artifacts
    source: Mapped[str] = mapped_column(
        String(16), nullable=False, default="pipeline", index=True
    )  # "pipeline" = real run | "test" = integration test — search_by_similarity always
       # filters to source="pipeline" so test artifacts never reach real agents
    output_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    embedding: Mapped[Optional[list[float]]] = mapped_column(Vector(3072), nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC), index=True
    )


class RunEvent(Base):
    """
    AuditLogger DB write path — one row per agent execution.

    Captures the full observability picture: which agent ran, on which model,
    for which ticker, in which run — with token counts, cost estimate, and latency.

    Used by M12 audit-report command to produce per-agent cost breakdowns.
    """

    __tablename__ = "run_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[Optional[uuid.UUID]] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("runs.id", ondelete="CASCADE"),
        nullable=True,
        index=True,
    )
    agent_name: Mapped[str] = mapped_column(String(64), nullable=False)
    ticker: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    model_used: Mapped[str] = mapped_column(String(64), nullable=False)
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    cost_usd_estimate: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    status: Mapped[str] = mapped_column(
        String(10), nullable=False, default=EventStatus.OK
    )  # EventStatus.OK | EventStatus.ERROR
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )


class RunDigestRecord(Base):
    """
    Stored FinalRecommendation per run — the list-runs / show-run source.

    digest_json holds the full FinalRecommendation serialised as JSON.
    formatted_text holds the plain-text digest (same as what's saved to runs/).
    """

    __tablename__ = "run_digests"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("runs.id", ondelete="CASCADE"),
        nullable=False, unique=True, index=True,
    )
    digest_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    formatted_text: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    digest_v3: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    sector_rotation: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    chain_dossiers: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    longitudinal_fund_dossiers: Mapped[Optional[list]] = mapped_column(JSON, nullable=True)
    narrative_dossier: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    # M46-ext — run-over-run delta (categorized drops from prior run's
    # action items, with deterministic evidence + LLM synthesis)
    run_diff: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    session_type: Mapped[str] = mapped_column(String(20), nullable=False, default="manual")
    action_item_count: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )
    sent_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)


class DataProvenance(Base):
    """
    News source tracking per (run × ticker) — feeds M12 provenance report.

    Each row is one news article that contributed to a run's analysis.
    source_url and published_at let users trace every claim in a digest
    back to its original source.
    """

    __tablename__ = "data_provenance"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[str] = mapped_column(String(36), nullable=False, index=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    source_name: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    source_url: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    agency_name: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    published_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    fetched_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )
    data_type: Mapped[str] = mapped_column(
        String(32), nullable=False, default="news"
    )  # "news" | "filing" | "analyst_report"


class ApiCall(Base):
    """
    External API call record — one row per HTTP request to FMP, Finnhub, FRED, MASSIVE, SEC EDGAR.

    Written by AuditLogger._write_api_call() on every provider call.
    Used by audit-report to surface per-provider success rates, latencies, and data yield.
    """

    __tablename__ = "api_calls"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    run_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True, index=True)
    provider: Mapped[str] = mapped_column(
        String(16), nullable=False
    )  # "fmp" | "finnhub" | "fred" | "massive" | "sec_edgar"
    endpoint: Mapped[str] = mapped_column(String(128), nullable=False)
    ticker: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    status_code: Mapped[int] = mapped_column(Integer, nullable=False, default=200)
    latency_ms: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    error_message: Mapped[Optional[str]] = mapped_column(
        String(256), nullable=True
    )  # truncated to 256 chars; full error in structlog
    result_count: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )  # records returned by this call; NULL = not tracked; 0 = empty/no data
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC)
    )


class TradeJournalEntry(Base):
    """M29.8-C — Full long-term history of closed trades.

    Mirrors PortfolioState.closed_trades (which is capped at the last 50 for
    JSON size) but stores the full history in Postgres. Dual-write happens
    after the JSON save in `pipeline/portfolio_trade.py` so the JSON is
    always source-of-truth and DB is best-effort durability. A replay
    routine syncs any JSON trades missing from the DB on each `portfolio
    trade` invocation, so a DB outage never causes data loss.

    The (portfolio_name, ticker, closed_date, shares, sold_price) tuple is
    unique-constrained: it forms the trade fingerprint used to dedupe
    replays. Multiple trades same ticker same day with different sizes/prices
    are independent rows (e.g. partial scale-outs).
    """

    __tablename__ = "trade_journal"
    __table_args__ = (
        UniqueConstraint(
            "portfolio_name", "ticker", "closed_date", "shares", "sold_price",
            name="uq_trade_journal_fingerprint",
        ),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4
    )
    portfolio_name: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    ticker: Mapped[str] = mapped_column(String(20), nullable=False, index=True)
    closed_date: Mapped[date] = mapped_column(Date, nullable=False, index=True)
    shares: Mapped[float] = mapped_column(Float, nullable=False)
    sold_price: Mapped[float] = mapped_column(Float, nullable=False)
    cost_basis_avg: Mapped[float] = mapped_column(Float, nullable=False)
    realized_gain: Mapped[float] = mapped_column(Float, nullable=False)

    # M29.8 journal fields — all optional (graceful fallback for legacy trades)
    entry_reason: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    market_regime_at_entry: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    stop_loss_at_entry: Mapped[Optional[float]] = mapped_column(Float, nullable=True)
    pyramid_plan_at_entry: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)
    exit_reason: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    post_mortem_note: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    holding_days: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    chive_alignment: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=lambda: datetime.now(UTC),
    )


class Run(Base):
    """Unified pipeline run record (v0.4.0).

    Collapses the previous RunRecord + RunIntent split into one row per
    pipeline run. `id` (UUID) is the only identity — child tables FK on it.

    Lifecycle:
      Daemon path (V2 cloud trigger):
        cloud inserts row with status='PENDING_START' →
        local daemon transitions STARTING → RUNNING → COMPLETE/FAILED.
      Standalone path (cron, direct CLI, daemon-startup):
        pipeline inserts row directly with status='RUNNING'.

    The status check constraint covers BOTH paths' historical states.

    See docs/superpowers/specs/2026-05-31-chive-v2-rhea-integration-design.md
    Section 11.1 for the full state diagram.
    """

    __tablename__ = "runs"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
    )
    portfolio: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    status: Mapped[str] = mapped_column(String(32), nullable=False, index=True)
    universe: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    custom_tickers: Mapped[Optional[list[str]]] = mapped_column(
        ARRAY(String(16)), nullable=True, default=None,
    )
    session_label: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    requested_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(UTC),
        server_default=text("now()"),
    )
    requested_by: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)
    picked_up_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    completed_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )
    error: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    failure_reason: Mapped[Optional[str]] = mapped_column(String(64), nullable=True)

    # ── Columns absorbed from the legacy RunRecord (pre-v0.4.0) ─────────────
    # All nullable — older intent-only rows didn't populate these.
    trigger_type: Mapped[Optional[str]] = mapped_column(String(30), nullable=True)
    session_type: Mapped[Optional[str]] = mapped_column(String(20), nullable=True)
    universe_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    portfolio_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    action_item_count: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    total_cost_usd: Mapped[Optional[float]] = mapped_column(
        Float, nullable=True, default=0.0,
    )
    started_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
    )

    __table_args__ = (
        CheckConstraint(
            "status IN ("
            "'PENDING_START','STARTING','RUNNING','COMPLETE','FAILED',"
            "'PENDING_STOP','STOPPING','CANCELLED',"
            "'PENDING_FORCE_STOP','STALE'"
            ")",
            name="ck_runs_status",
        ),
    )


class DaemonStatus(Base):
    """M33 / V2 — Local CHIVE daemon health + readiness signal.

    The local daemon upserts this row every poll interval (~30s). The cloud
    webserver reads it to determine if the daemon is online (heartbeat < 60s),
    stale (60s-5min), or down (>5min). Per spec Section 12.
    """

    __tablename__ = "daemon_status"

    daemon_id: Mapped[str] = mapped_column(String(64), primary_key=True)
    last_heartbeat_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(UTC),
        server_default=text("now()"),
    )
    poll_interval_seconds: Mapped[int] = mapped_column(
        Integer, nullable=False, default=30, server_default=text("30"),
    )
    hostname: Mapped[Optional[str]] = mapped_column(String(128), nullable=True)
    pipeline_version: Mapped[Optional[str]] = mapped_column(String(32), nullable=True)
    current_run_id: Mapped[Optional[str]] = mapped_column(String(36), nullable=True)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False,
        default=lambda: datetime.now(UTC),
        server_default=text("now()"),
    )


# ── Backwards-compatibility aliases (v0.4.0 unified-runs refactor) ───────────
# RunIntent was renamed to Run; RunRecord was deleted (its columns absorbed).
# These aliases let downstream code (chive pipeline, chive-backend) keep their
# old imports working until they migrate to `Run` in subsequent commits
# (M35 steps 2-5).
RunIntent = Run
RunRecord = Run


class ChartSnapshot(Base):
    """One row per (run, ticker) — persists OHLCV bars + indicators + annotations
    the pipeline analyzed during a run, so the chive-web Digest tab can render
    interactive Lightweight Charts that match exactly what CHIVE saw.

    Bars are a JSON array of {t, o, h, l, c, v}; indicators is a free-form JSON
    object the pipeline chooses (e.g. ma_50, ma_200, vwap, atr); annotations
    likewise (distribution_days, pivot_price, stage, etc).
    """

    __tablename__ = "chart_snapshots"

    run_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("runs.id", ondelete="CASCADE"),
        primary_key=True,
    )
    ticker: Mapped[str] = mapped_column(String(16), primary_key=True)
    bars: Mapped[list] = mapped_column(JSONB, nullable=False)
    indicators: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=dict, server_default=text("'{}'::jsonb"),
    )
    annotations: Mapped[dict] = mapped_column(
        JSONB, nullable=False, default=dict, server_default=text("'{}'::jsonb"),
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=text("now()"),
    )
